import { useEffect, useRef, useState, forwardRef, useImperativeHandle, useCallback } from "react";
import { usePlayerState } from "./UsePlayerState";

// ─── Language code → display name ─────────────────────────────────────────────

const LANG_MAP = {
    eng: "English",
    en: "English",
    hin: "Hindi",
    hi: "Hindi",
    ben: "Bangla",
    bn: "Bangla",
    jpn: "Japanese",
    ja: "Japanese",
    fra: "French",
    fr: "French",
    spa: "Spanish",
    es: "Spanish",
    ara: "Arabic",
    ar: "Arabic",
    deu: "German",
    de: "German",
    kor: "Korean",
    ko: "Korean",
    zho: "Chinese",
    zh: "Chinese",
    rus: "Russian",
    ru: "Russian",
    ita: "Italian",
    it: "Italian",
    por: "Portuguese",
    pt: "Portuguese",
    tur: "Turkish",
    tr: "Turkish",
    urd: "Urdu",
    ur: "Urdu",
    tam: "Tamil",
    ta: "Tamil",
    tel: "Telugu",
    te: "Telugu",
    mal: "Malayalam",
    ml: "Malayalam",
    kan: "Kannada",
    kn: "Kannada",
    pan: "Punjabi",
    pa: "Punjabi",
    mar: "Marathi",
    mr: "Marathi",
    guj: "Gujarati",
    gu: "Gujarati",
    vie: "Vietnamese",
    vi: "Vietnamese",
    tha: "Thai",
    th: "Thai",
    pol: "Polish",
    pl: "Polish",
    dut: "Dutch",
    nld: "Dutch",
    nl: "Dutch",
    per: "Persian",
    fas: "Persian",
    fa: "Persian",
};

function resolveLanguageName(track, index) {
    const lang = (track.lang || track.language || "").toLowerCase();
    if (LANG_MAP[lang] && lang !== "und") return LANG_MAP[lang];
    const name = track.name || "";
    // FIX: when the HLS manifest's audio rendition has no NAME= attribute
    // (source file had no language tag, or a backend build predating the
    // name: fix served a stale session), hls.js falls back to its own
    // internal label — group-id + "_" + index. Our audio group id is
    // literally "audio", so that fallback is indistinguishable from a real
    // name UNLESS we specifically recognize and reject that exact pattern.
    // This makes the player correct regardless of what the manifest
    // actually contains, instead of depending on the backend always
    // getting NAME= right.
    const looksAutoGenerated = /^audio[_-]?\d+$/i.test(name.trim());
    if (name && !looksAutoGenerated) return name;
    if (typeof index === "number") return `Track${index + 1}`;
    return lang && lang !== "und" ? lang.toUpperCase() : "Unknown";
}

// ─── Aspect ratio CSS ─────────────────────────────────────────────────────────

function getAspectStyle(aspectRatio) {
    switch (aspectRatio) {
        case "fill":
            return { objectFit: "cover", width: "100%", height: "100%" };
        case "1:1":
            return { objectFit: "contain", width: "100%", aspectRatio: "1/1" };
        case "stretch":
            return { objectFit: "fill", width: "100%", height: "100%" };
        default:
            return { objectFit: "contain", width: "100%", height: "100%" };
    }
}

// ─── 16:9 / 4:3 exact pixel box ───────────────────────────────────────────────
//
// FIX (top-gap bug): these modes used to set width:"100%" + CSS aspect-ratio
// and let the browser derive height from width. Whenever that derived height
// didn't match the container's real height, the leftover gap landed unevenly
// (usually pinned to the top) instead of splitting evenly above/below — the
// grid+placeItems:center wrapper centers whatever box the video resolves to,
// but it can't fix a box that was sized wrong in the first place.
//
// Fix: compute the exact pixel width/height ourselves from the container's
// real dimensions (same approach as computeLetterboxBox for "auto"), so the
// box is correct before it ever reaches the DOM — centering then "just works"
// because there's no ambiguous leftover space to begin with.
function computeFixedRatioBox(containerW, containerH, ratioW, ratioH) {
    if (!containerW || !containerH) return { width: "100%", height: "100%" };
    const targetRatio = ratioW / ratioH;
    const calculatedWidth = containerH * targetRatio;
    if (calculatedWidth <= containerW) {
        return { width: Math.round(calculatedWidth), height: Math.round(containerH) };
    }
    // Doesn't fit by height — scale down to fit by width instead, same
    // fallback branch the 16:9 spec calls for, applied to both ratios so
    // neither can ever overflow the container on unusual screen shapes.
    return { width: Math.round(containerW), height: Math.round(containerW / targetRatio) };
}

// ─── Intrinsic-dimension letterbox calc ───────────────────────────────────────
//
// FIX (ultra-wide top-align bug): relying on CSS object-fit:contain with a
// width:100%/height:100% box is ambiguous on some mobile browsers (Android
// Chrome/Firefox/Samsung Internet/WebView) — the contain box is computed from
// the parent's flex-resolved cross-axis size, which can settle before video
// metadata loads, or interact oddly with cinematic (<1) aspect ratios vs the
// container's portrait aspect, producing a top-anchored render instead of a
// vertically centered one.
//
// Fix: compute the exact letterboxed pixel box ourselves from the video's
// real intrinsic dimensions (videoWidth/videoHeight) and the container's
// real dimensions, then set explicit width/height in px on the <video>
// element. No object-fit guesswork — same approach YouTube/VLC use.
function computeLetterboxBox(containerW, containerH, videoW, videoH) {
    if (!containerW || !containerH || !videoW || !videoH) {
        return { width: "100%", height: "100%" };
    }
    const containerRatio = containerW / containerH;
    const videoRatio = videoW / videoH;
    if (videoRatio > containerRatio) {
        // Video is wider relative to container → fit width, letterbox top/bottom
        const width = containerW;
        const height = Math.round(containerW / videoRatio);
        return { width, height };
    } else {
        // Video is taller/narrower relative to container → fit height, letterbox sides
        const height = containerH;
        const width = Math.round(containerH * videoRatio);
        return { width, height };
    }
}

// ─── Adaptive HLS config by network / media type ──────────────────────────────

function getHlsConfig() {
    return {
        enableWorker: true,
        workerPath: undefined,
        lowLatencyMode: false,

        // FIX (Report-19): HLS EVENT playlist type makes hls.js treat the stream
        // as a live broadcast — it chases the live edge and prevents seeking ahead.
        // Force VOD mode so hls.js treats all playlists as on-demand, enabling
        // full seeking regardless of playlist type in the manifest.
        liveDurationInfinity: false,
        // Treat EVENT playlists as VOD once loaded (don't poll for new segments
        // after the current batch — the transcoder appends them naturally).
        liveBackBufferLength: Infinity,

        // Back-buffer: keep 90s behind so user can seek back without refetch
        backBufferLength: 90,

        // Forward buffer: 30s is optimal for most connections
        // HLS.js will auto-grow up to maxMaxBufferLength during smooth playback
        maxBufferLength: 30,
        maxMaxBufferLength: 120,

        // Start loading fragments before play is triggered for instant start
        startFragPrefetch: true,
        startLevel: -1, // auto-select start level

        // Aggressive retry on network errors (helps on home WiFi)
        fragLoadingMaxRetry: 8,
        fragLoadingRetryDelay: 300,
        fragLoadingMaxRetryTimeout: 6000,
        fragLoadingTimeOut: 30_000,

        manifestLoadingMaxRetry: 4,
        manifestLoadingRetryDelay: 500,
        manifestLoadingTimeOut: 20_000,

        levelLoadingMaxRetry: 4,
        levelLoadingTimeOut: 20_000,

        // ABR: keep best quality for longer
        abrEwmaFastLive: 3,
        abrEwmaSlowLive: 9,
        abrEwmaFastVoD: 4,
        abrEwmaSlowVoD: 15,
        abrBandWidthFactor: 0.95,
        abrBandWidthUpFactor: 0.7,

        // Better seeking
        maxSeekHole: 2,

        // Stall recovery
        nudgeMaxRetry: 6,
        nudgeOffset: 0.2,

        // Seamless audio-track switching (hls.nextAudioTrack, used in the
        // audio-track sync effect below) — controls how much forward
        // buffer is retained when scheduling the switch. Smaller values
        // switch faster but with less safety margin against a brief stall;
        // HLS.js's own default is 0.25s, set explicitly here for clarity.
        nextAudioTrackBufferFlushForwardOffset: 0.25,

        // HLS.js debug log (only in dev)
        debug: false,
    };
}

// ─── VideoCore ────────────────────────────────────────────────────────────────

/**
 * VideoCore — handles ALL low-level video/HLS lifecycle.
 *
 * Key improvements over original:
 *  1. Module-level deduplication + cancellation guard on async HLS import.
 *  2. Smart stall recovery: nudge currentTime + startLoad on BUFFER_STALLED.
 *  3. Quality/audio switch by ID (not array index).
 *  4. Better duration resolution from MANIFEST_PARSED.
 *  5. Adaptive buffering config for large remux/4K files.
 *  6. Network error auto-retry with exponential backoff.
 */
const VideoCore = forwardRef(function VideoCore({ streamUrl, onVideoClick, onRetry, mediaDuration, onReadyToSeek, onHlsCreated, zoomScale = 1, panX = 0, panY = 0 }, ref) {
    const videoRef = useRef(null);
    const wrapperRef = useRef(null);
    const hlsRef = useRef(null);
    const retryCount = useRef(0);
    const latestOnReadyToSeek = useRef(onReadyToSeek);
    const { state, actions } = usePlayerState();
    const latestPlaying = useRef(state.playing);
    // ── Audio-switch race/watchdog refs (additive — does not touch existing
    // quality/level logic). audioSwitchBusy prevents overlapping switches
    // when the user taps tracks rapidly; positionBeforeAudioSwitch +
    // audioSwitchWatchdogTimer give every switch path (nextAudioTrack OR the
    // legacy hls.audioTrack fallback OR AUDIO_TRACK_SWITCHED) a single
    // shared safety net that resumes play / restores position if HLS.js
    // never confirms the switch or fires a stray pause mid-flush.
    const audioSwitchBusy = useRef(false);
    const positionBeforeAudioSwitch = useRef(0);
    const pendingAudioTrackId = useRef(null);
    const audioSwitchWatchdogTimer = useRef(null);

    // Intrinsic video dimensions (real decoded size, not container size) +
    // live container box size — recomputed on metadata load, resize, rotation,
    // and fullscreen transitions so the letterbox math always matches reality.
    const [videoDims, setVideoDims] = useState({ w: 0, h: 0 });
    const [containerDims, setContainerDims] = useState({ w: 0, h: 0 });

    // ── Track container size (resize / rotation / fullscreen enter+exit) ─────
    useEffect(() => {
        const el = wrapperRef.current;
        if (!el) return;

        const remeasure = () => {
            const rect = el.getBoundingClientRect();
            setContainerDims({ w: rect.width, h: rect.height });
        };

        let ro = null;
        if (typeof ResizeObserver !== "undefined") {
            ro = new ResizeObserver((entries) => {
                const entry = entries[0];
                if (!entry) return;
                const { width, height } = entry.contentRect;
                setContainerDims({ w: width, h: height });
            });
            ro.observe(el);
        }
        remeasure();

        // FIX (rotation overflow): getBoundingClientRect() on the wrapper can
        // briefly report STALE (pre-rotation) numbers right as the device
        // rotates — the video's px box gets computed from that stale,
        // larger-than-actual container size and visibly overflows the new
        // (now actually smaller on one axis) viewport until a later delayed
        // remeasure corrects it. window.innerWidth/innerHeight update
        // synchronously with the orientation event itself (no layout-query
        // race), so snap to those FIRST as an immediate correct-or-better
        // estimate, then let the getBoundingClientRect remeasures refine it
        // (e.g. for safe-area/cutout adjustments rect captures that raw
        // innerWidth/innerHeight don't).
        const snapToViewport = () => {
            setContainerDims({ w: window.innerWidth, h: window.innerHeight });
        };

        const remeasureSettled = () => {
            snapToViewport();
            remeasure();
            requestAnimationFrame(remeasure);
            setTimeout(remeasure, 100);
            setTimeout(remeasure, 350);
        };
        document.addEventListener("fullscreenchange", remeasureSettled);
        document.addEventListener("webkitfullscreenchange", remeasureSettled);
        window.addEventListener("orientationchange", remeasureSettled);

        return () => {
            ro?.disconnect();
            document.removeEventListener("fullscreenchange", remeasureSettled);
            document.removeEventListener("webkitfullscreenchange", remeasureSettled);
            window.removeEventListener("orientationchange", remeasureSettled);
        };
    }, []);

    // ── Track intrinsic video dimensions ──────────────────────────────────────
    useEffect(() => {
        const video = videoRef.current;
        if (!video) return;
        const updateDims = () => {
            if (video.videoWidth && video.videoHeight) {
                setVideoDims({ w: video.videoWidth, h: video.videoHeight });
            }
        };
        // loadedmetadata fires earliest with real dims; resize fires on quality
        // switch (HLS level change can alter decoded resolution).
        video.addEventListener("loadedmetadata", updateDims);
        video.addEventListener("resize", updateDims);
        updateDims(); // in case metadata already loaded (e.g. fast cache hit)
        return () => {
            video.removeEventListener("loadedmetadata", updateDims);
            video.removeEventListener("resize", updateDims);
        };
    }, [streamUrl]);

    // Reset intrinsic dims when stream changes so stale dims don't briefly
    // apply to the new video before its own metadata loads.
    useEffect(() => {
        setVideoDims({ w: 0, h: 0 });
    }, [streamUrl]);

    // Keep ref current so closed-over handlers always call latest callback
    useEffect(() => {
        latestOnReadyToSeek.current = onReadyToSeek;
    }, [onReadyToSeek]);

    useEffect(() => {
        latestPlaying.current = state.playing;
    }, [state.playing]);

    // Expose raw video element to parent
    useImperativeHandle(ref, () => videoRef.current, []);

    // ── HLS.js / direct-play initialization ──────────────────────────────────
    useEffect(() => {
        if (!streamUrl || !videoRef.current) return;
        const video = videoRef.current;
        let cancelled = false;

        // Reset retry count on new stream
        retryCount.current = 0;

        const isHLS = streamUrl.includes(".m3u8");

        if (isHLS) {
            import("hls.js").then(({ default: Hls }) => {
                if (cancelled) return;

                // Native HLS (Safari / iPhone)
                if (!Hls.isSupported()) {
                    video.src = streamUrl;
                    return;
                }

                // Destroy previous instance cleanly
                if (hlsRef.current) {
                    const old = hlsRef.current;
                    hlsRef.current = null;
                    old.destroy();
                }

                const hls = new Hls(getHlsConfig());
                hlsRef.current = hls;
                // Notify parent so it can call hls.startLoad() for accurate resume seeking
                onHlsCreated?.(hls);
                hls.loadSource(streamUrl);
                hls.attachMedia(video);

                // ── MANIFEST_PARSED ─────────────────────────────────────────
                hls.on(Hls.Events.MANIFEST_PARSED, (_, data) => {
                    if (cancelled) return;

                    // Quality levels
                    const levels = hls.levels.map((l, i) => ({
                        index: i,
                        height: l.height,
                        width: l.width,
                        bitrate: l.bitrate,
                        label: l.height ? `${l.height}p` : `Level ${i}`,
                    }));
                    actions.setQualityLevels(levels);
                    actions.setActiveQuality(-1); // start on auto

                    // Audio tracks
                    const tracks = (hls.audioTracks || []).map((t, i) => ({
                        index: i,
                        id: t.id,
                        name: resolveLanguageName(t, i),
                        lang: t.lang || t.language || "",
                        default: t.default || false,
                    }));
                    actions.setAudioTracks(tracks);
                    const defIdx = tracks.findIndex((t) => t.default);
                    actions.setActiveAudioTrack(defIdx >= 0 ? defIdx : 0);

                    // FIX (Report-21): Source files often have non-zero starting PTS
                    // (e.g. Interstellar begins at 7.304s). -copyts preserves these
                    // timestamps in segments, so the browser's <video> currentTime
                    // jumps to 7.304s immediately. Force hls.startPosition = 0 so
                    // HLS.js normalises the timeline baseline to zero before play.
                    hls.startPosition = 0;

                    actions.setError(null);
                    actions.setReady(true);
                    latestOnReadyToSeek.current?.();
                    actions.setPlaying(true);
                    video.play().catch(() => {});
                });

                // ── LEVEL_LOADED (duration source) ──────────────────────
                hls.on(Hls.Events.LEVEL_LOADED, (_, data) => {
                    if (cancelled) return;
                    const totalduration = data?.details?.totalduration;
                    // FIX (Report-19): HLS EVENT playlist totalduration grows as FFmpeg
                    // transcodes — it starts tiny (17s) and expands. This makes the
                    // seekbar shrink/grow continuously and confuses hls.js into live mode.
                    // Always prefer mediaDuration (real ffprobe duration from PlayerPage)
                    // when it's available — it's the true full-film duration.
                    // Only fall back to totalduration if mediaDuration is absent.
                    const hlsDur = totalduration && totalduration > 0 ? totalduration : 0;
                    const realDur = mediaDuration && mediaDuration > 0 ? mediaDuration : 0;
                    const best = realDur > 0 ? realDur : hlsDur;
                    if (best > 0) actions.setDuration(best);
                });

                // ── LEVEL_SWITCHED ──────────────────────────────────────────
                hls.on(Hls.Events.LEVEL_SWITCHED, (_, data) => {
                    if (cancelled) return;
                    actions.setActiveQuality(hls.autoLevelEnabled ? -1 : data.level);
                });

                // ── AUDIO_TRACKS_UPDATED ─────────────────────────────────────
                // Canonical HLS.js event for "audio tracks were discovered
                // from the manifest's EXT-X-MEDIA lines" — more reliable
                // than reading hls.audioTracks synchronously inside
                // MANIFEST_PARSED, which has known timing/empty-array issues
                // in some HLS.js versions even with a structurally valid
                // manifest. This is the primary population path now; the
                // read inside MANIFEST_PARSED above is kept as a fallback.
                hls.on(Hls.Events.AUDIO_TRACKS_UPDATED, (_, data) => {
                    if (cancelled) return;
                    const updatedTracks = (data?.audioTracks || hls.audioTracks || []).map((t, i) => ({
                        index: i,
                        id: t.id,
                        name: resolveLanguageName(t, i),
                        lang: t.lang || t.language || "",
                        default: t.default || false,
                    }));
                    if (updatedTracks.length === 0) return; // nothing to report yet
                    actions.setAudioTracks(updatedTracks);
                    const defIdx = updatedTracks.findIndex((t) => t.default);
                    actions.setActiveAudioTrack(defIdx >= 0 ? defIdx : 0);
                });

                // ── AUDIO_TRACK_SWITCHED ────────────────────────────────────
                hls.on(Hls.Events.AUDIO_TRACK_SWITCHED, (_, data) => {
                    if (cancelled) return;
                    const idx = (hls.audioTracks || []).findIndex((t) => t.id === data.id);
                    actions.setActiveAudioTrack(idx >= 0 ? idx : 0);

                    // Only run the drift-restore/stall-nudge safety net when
                    // this event corresponds to a switch WE actually asked
                    // for (see pendingAudioTrackId, set by the sync effect
                    // below right before calling nextAudioTrack/audioTrack).
                    // HLS.js also fires this same event for its own internal
                    // default-track selection at video start — that case has
                    // nothing to "restore" and running this logic there is
                    // what caused fresh-video stalls / clobbered resume-seek.
                    const wasOurSwitch = pendingAudioTrackId.current === data.id;
                    if (audioSwitchWatchdogTimer.current) {
                        clearTimeout(audioSwitchWatchdogTimer.current);
                        audioSwitchWatchdogTimer.current = null;
                    }
                    audioSwitchBusy.current = false;
                    pendingAudioTrackId.current = null;
                    if (!wasOurSwitch) return;

                    const v = videoRef.current;
                    if (!v) return;

                    // Switching to a separate-rendition audio track (this
                    // backend's multi-audio layout — not in-band-muxed audio)
                    // can briefly pause the underlying MSE pipeline while it
                    // flushes and reloads the new track's buffer, and can
                    // occasionally reset currentTime to the start of the
                    // newly-loaded audio fragment. Correct both: restore the
                    // pre-switch position if it drifted, then resume playback
                    // if the user's actual intent was still "playing".
                    const savedPos = positionBeforeAudioSwitch.current;
                    if (savedPos > 0 && Math.abs(v.currentTime - savedPos) > 1.5) {
                        v.currentTime = savedPos;
                    }
                    if (latestPlaying.current && v.paused) {
                        v.play().catch(() => {});
                    }

                    // Extra check: the audio-rendition swap can leave the
                    // native <video> element reporting NOT paused (so the
                    // v.paused branch above never fires) while the actual
                    // decode pipeline is silently frozen — no BUFFER_STALLED
                    // event gets emitted for this specific stall, so HLS.js's
                    // own recovery never kicks in either, and the only way to
                    // unstick it manually was toggling pause/play. Detect a
                    // true freeze (currentTime not advancing while supposedly
                    // playing) and apply the exact same nudge + startLoad()
                    // recovery BUFFER_STALLED already uses elsewhere in this
                    // file, instead of waiting on a manual toggle.
                    if (latestPlaying.current) {
                        const tBefore = v.currentTime;
                        setTimeout(() => {
                            const vv = videoRef.current;
                            if (!vv || vv.paused) return;
                            if (Math.abs(vv.currentTime - tBefore) < 0.05) {
                                if (vv.readyState > 2 && vv.currentTime > 0) {
                                    vv.currentTime += 0.1;
                                }
                                hls.startLoad();
                                vv.play().catch(() => {});
                            }
                        }, 800);
                    }
                });

                // ── BUFFER_STALLED (stall recovery) ────────────────────────
                hls.on(Hls.Events.BUFFER_STALLED, () => {
                    if (cancelled) return;
                    actions.setBuffering(true);
                    actions.incrementStall();
                    // Nudge playhead slightly to unstick browser decoder
                    if (video.readyState > 2 && video.currentTime > 0) {
                        video.currentTime += 0.1;
                    }
                    hls.startLoad();
                });

                // ── FRAG_LOADED (clear buffering indicator) ─────────────────
                hls.on(Hls.Events.FRAG_LOADED, (_, data) => {
                    if (cancelled) return;
                    // Update duration from loaded fragment data (HLS live/event streams)
                    if (data?.frag?.duration) {
                        const v = videoRef.current;
                        if (v && isFinite(v.duration) && v.duration > 0) {
                            actions.setDuration(v.duration);
                        }
                    }
                    // Clear buffering state once at least one fragment loaded
                    actions.setBuffering(false);
                });

                // ── ERROR ────────────────────────────────────────────────────
                hls.on(Hls.Events.ERROR, (_, data) => {
                    if (cancelled || !data.fatal) return;

                    const status = data.response?.code;

                    if (status === 429) {
                        hls.destroy();
                        hlsRef.current = null;
                        actions.setError("Stream rate-limited. Please wait and try again.");
                        return;
                    }
                    if (status === 404) {
                        hls.destroy();
                        hlsRef.current = null;
                        actions.setError("Stream not found. Go back and try again.");
                        return;
                    }

                    switch (data.type) {
                        case Hls.ErrorTypes.NETWORK_ERROR:
                            // Exponential backoff retry
                            if (retryCount.current < 5) {
                                retryCount.current++;
                                const delay = Math.min(500 * 2 ** retryCount.current, 10000);
                                setTimeout(() => {
                                    if (!cancelled) hls.startLoad();
                                }, delay);
                            } else {
                                actions.setError("Network error. Check connection and try again.");
                            }
                            break;
                        case Hls.ErrorTypes.MEDIA_ERROR:
                            if (retryCount.current < 3) {
                                retryCount.current++;
                                hls.recoverMediaError();
                            } else {
                                hls.swapAudioCodec();
                                hls.recoverMediaError();
                            }
                            break;
                        default:
                            hls.destroy();
                            hlsRef.current = null;
                            actions.setError("Unable to play stream. Please try again.");
                    }
                });
            });
        } else {
            // ── Direct play (MP4, MKV via range requests, etc.) ───────────────
            video.src = streamUrl;
            actions.setReady(false);

            const onLoadedMeta = () => {
                // Don't seek yet — let useProgress handle resume
                if (isFinite(video.duration) && video.duration > 0) {
                    actions.setDuration(video.duration);
                }
            };

            const onCanPlay = () => {
                actions.setError(null);
                actions.setBuffering(false);

                // Native audio track enumeration
                if (video.audioTracks && video.audioTracks.length > 1) {
                    const tracks = Array.from(video.audioTracks).map((t, i) => ({
                        index: i,
                        id: t.id,
                        name: resolveLanguageName({ lang: t.language, name: t.label }, i),
                        lang: t.language || "",
                        default: t.enabled,
                    }));
                    actions.setAudioTracks(tracks);
                    const activeIdx = tracks.findIndex((t) => t.default);
                    actions.setActiveAudioTrack(activeIdx >= 0 ? activeIdx : 0);
                }
                // Allow useProgress to seek to resume position before play starts
                latestOnReadyToSeek.current?.();
                actions.setReady(true);
            };

            video.addEventListener("loadedmetadata", onLoadedMeta, { once: true });
            video.addEventListener("canplay", onCanPlay, { once: true });

            return () => {
                cancelled = true;
                video.removeEventListener("loadedmetadata", onLoadedMeta);
                video.removeEventListener("canplay", onCanPlay);
                if (hlsRef.current) {
                    hlsRef.current.destroy();
                    hlsRef.current = null;
                }
                // FIX (Report-20): Do NOT set video.src = "" here.
                // StrictMode cleanup fires on first mount then re-mounts immediately.
                // src="" makes browser try to load current page URL as media →
                // DEMUXER_ERROR_COULD_NOT_OPEN. HLS.js destroy() detaches MediaSource
                // cleanly. Direct play: next effect sets new src itself.
            };
        }

        return () => {
            cancelled = true;
            if (hlsRef.current) {
                hlsRef.current.destroy();
                hlsRef.current = null;
            }
            // FIX (Report-20): Do NOT set video.src = "" — see comment above.
            // StrictMode double-invoke causes DEMUXER_ERROR_COULD_NOT_OPEN.
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [streamUrl]);

    // ── Sync HLS quality level ────────────────────────────────────────────────
    useEffect(() => {
        if (!hlsRef.current) return;
        // autoLevelEnabled is a read-only getter in current HLS.js — it can't
        // be assigned directly (that's what was throwing "Cannot set property
        // autoLevelEnabled... which has only a getter"). The documented way
        // to re-enable automatic quality switching is currentLevel = -1, the
        // same sentinel used everywhere else in HLS.js for "go back to auto".
        hlsRef.current.currentLevel = state.activeQuality === -1 ? -1 : state.activeQuality;
    }, [state.activeQuality]);

    // ── Sync audio track by HLS ID (not array index) ─────────────────────────
    useEffect(() => {
        const hls = hlsRef.current;
        if (!hls) return;
        const track = hls.audioTracks?.[state.activeAudioTrack];
        if (!track || track.id === hls.audioTrack) return;

        // FIX (regression): AUDIO_TRACKS_UPDATED fires and calls
        // setActiveAudioTrack(defaultIndex) BEFORE hls.js has internally
        // picked its own default (hls.audioTrack is still -1/undefined at
        // that instant). That made this effect treat the video's normal
        // startup track selection as if it were a real user-initiated
        // switch — running the drift-restore/watchdog/stall-nudge machinery
        // on every video open. That's what broke resume-seek (the watchdog
        // stomped the position useProgress was seeking to) and caused the
        // fresh-load stall (extra hls.startLoad() during initial buffering).
        // Only treat this as a real switch once HLS.js already has an
        // established (non-negative) audio track — i.e. skip entirely for
        // the very first automatic selection and let HLS.js's own default
        // pick stand untouched.
        const isInitialAutoSelection = hls.audioTrack == null || hls.audioTrack < 0;
        if (isInitialAutoSelection) return;

        // Guard: ignore a new switch request while one is already in-flight
        // (prevents rapid-tap race where a second switch fires before the
        // first one settles, which was one path that could leave HLS.js in
        // a state where neither AUDIO_TRACK_SWITCHED nor the drift-restore
        // ever ran, surfacing as "stuck paused at 0:00").
        if (audioSwitchBusy.current) return;
        audioSwitchBusy.current = true;
        pendingAudioTrackId.current = track.id;

        const positionBeforeSwitch = videoRef.current?.currentTime || 0;
        positionBeforeAudioSwitch.current = positionBeforeSwitch;

        const restoreIfDrifted = () => {
            const v = videoRef.current;
            audioSwitchBusy.current = false;
            audioSwitchWatchdogTimer.current = null;
            if (!v) return;
            // Only correct an unexpected jump — a few hundred ms of
            // natural drift from normal seeking/buffering is fine and
            // shouldn't be fought.
            if (Math.abs(v.currentTime - positionBeforeSwitch) > 1.5) {
                v.currentTime = positionBeforeSwitch;
            }
            if (latestPlaying.current && v.paused) {
                v.play().catch(() => {});
            }
            // Same "reported playing but actually frozen" check as the
            // AUDIO_TRACK_SWITCHED handler — this watchdog only runs when
            // that event never fired at all, so it's the last line of
            // defense against the silent-freeze case (no BUFFER_STALLED,
            // v.paused stays false, nothing else would ever unstick it
            // besides a manual pause/play toggle).
            if (latestPlaying.current) {
                const tBefore = v.currentTime;
                setTimeout(() => {
                    const vv = videoRef.current;
                    const h = hlsRef.current;
                    if (!vv || vv.paused) return;
                    if (Math.abs(vv.currentTime - tBefore) < 0.05) {
                        if (vv.readyState > 2 && vv.currentTime > 0) {
                            vv.currentTime += 0.1;
                        }
                        h?.startLoad();
                        vv.play().catch(() => {});
                    }
                }, 800);
            }
        };

        // hls.nextAudioTrack is HLS.js's purpose-built seamless-switch API —
        // it schedules the change without flushing the current buffer or
        // interrupting playback, avoiding the stall/seek-fallback behavior
        // that plain hls.audioTrack causes (HLS.js had to fall back to
        // re-seeking when it couldn't correlate buffered content across
        // renditions, which is what was surfacing as "stops and resets to
        // 0:00"). Only available in newer HLS.js — feature-detected here,
        // falls back to the old assignment + position-restore safeguard
        // for older versions.
        if ("nextAudioTrack" in hls) {
            hls.nextAudioTrack = track.id;
            // Watchdog: AUDIO_TRACK_SWITCHED (which clears audioSwitchBusy
            // and does its own drift-restore) is expected to fire shortly
            // after. If it never fires — dropped event, HLS.js version quirk,
            // or the swap silently no-op'd — this timeout runs the same
            // restore logic so the player never gets stuck paused/at 0:00
            // and the busy-flag always clears for the next attempt.
            if (audioSwitchWatchdogTimer.current) clearTimeout(audioSwitchWatchdogTimer.current);
            audioSwitchWatchdogTimer.current = setTimeout(restoreIfDrifted, 2500);
            return;
        }

        // ── Fallback for HLS.js versions without nextAudioTrack ──────────
        hls.audioTrack = track.id;

        // Old hls.js versions can't correlate buffered content across the
        // audio-only rendition switch and fall back to an internal re-seek —
        // which can land before the target's segment for the NEW track has
        // actually buffered yet. A single fixed-delay check can fire before
        // that segment is seekable. Poll video.seekable the same way the
        // rest of this app already does for resume-seeking (see useProgress
        // deferredSeek) instead of trusting one 400ms timeout.
        if (audioSwitchWatchdogTimer.current) clearTimeout(audioSwitchWatchdogTimer.current);
        let pollAttempts = 0;
        const MAX_POLL_ATTEMPTS = 10; // 10 × 300ms = 3s max wait
        const pollAndRestore = () => {
            pollAttempts++;
            const v = videoRef.current;
            if (!v) {
                restoreIfDrifted();
                return;
            }
            let targetSeekable = true;
            try {
                const seekable = v.seekable;
                targetSeekable = seekable.length === 0 || seekable.end(seekable.length - 1) + 1 >= positionBeforeSwitch;
            } catch {
                targetSeekable = true;
            }
            if (targetSeekable || pollAttempts >= MAX_POLL_ATTEMPTS) {
                restoreIfDrifted();
                return;
            }
            audioSwitchWatchdogTimer.current = setTimeout(pollAndRestore, 300);
        };
        audioSwitchWatchdogTimer.current = setTimeout(pollAndRestore, 400);
    }, [state.activeAudioTrack]);

    // Clear any pending audio-switch watchdog on unmount so it can't fire
    // against a torn-down video element.
    useEffect(() => {
        return () => {
            if (audioSwitchWatchdogTimer.current) {
                clearTimeout(audioSwitchWatchdogTimer.current);
                audioSwitchWatchdogTimer.current = null;
            }
        };
    }, []);

    // ── Shared Web Audio graph: Volume Boost + 5-Band Equalizer ───────────────
    //
    // <video>.volume natively caps at 1.0 — pushing louder, or applying any
    // frequency-selective EQ, requires routing through Web Audio. This is a
    // ONE-WAY change: createMediaElementSource() can only be called ONCE
    // per <video> element, ever — so Volume Boost and EQ MUST share the
    // exact same source/context; they cannot each create their own. Graph:
    //   source → b60 → b230 → b910 → b4000 → b14000 → gain → destination
    // Lazily created on first actual use of EITHER feature. If neither is
    // ever touched, native <video>.volume keeps working with zero Web Audio
    // involvement at all.
    //
    // FIX: this used to be a 3-band chain (bass/mid/treble) reading
    // state.eqBands.bass/mid/treble — but UsePlayerState.jsx and
    // PlayerControls.jsx have always used a 5-band shape
    // (b60/b230/b910/b4000/b14000, with 11 presets tuned for 5 distinct
    // bands). Since state.eqBands never had .bass/.mid/.treble, every band
    // silently destructured to 0 — the EQ sliders/presets had zero audible
    // effect regardless of what the user picked. Expanded to a real 5-band
    // chain (standard graphic-EQ topology: low-shelf, 3× peaking, high-shelf)
    // matching the state shape that already exists everywhere else, rather
    // than collapsing the UI/presets down to 3 bands — keeps this fix
    // contained to this one file instead of touching state/UI/preset data.
    //
    // Defensive: AudioContext requires a prior user gesture on most
    // browsers — if construction fails, both features silently have no
    // audible effect rather than crashing playback.
    const audioCtxRef = useRef(null);
    const gainNodeRef = useRef(null);
    const sourceNodeRef = useRef(null);
    const eqBandsRef = useRef({ b60: null, b230: null, b910: null, b4000: null, b14000: null });

    const ensureAudioGraph = useCallback(() => {
        const video = videoRef.current;
        if (!video || sourceNodeRef.current) return sourceNodeRef.current ? true : false;
        try {
            const Ctx = window.AudioContext || window.webkitAudioContext;
            const ctx = new Ctx();
            const source = ctx.createMediaElementSource(video);

            const b60 = ctx.createBiquadFilter();
            b60.type = "lowshelf";
            b60.frequency.value = 60;
            b60.gain.value = 0;

            const b230 = ctx.createBiquadFilter();
            b230.type = "peaking";
            b230.frequency.value = 230;
            b230.Q.value = 1;
            b230.gain.value = 0;

            const b910 = ctx.createBiquadFilter();
            b910.type = "peaking";
            b910.frequency.value = 910;
            b910.Q.value = 1;
            b910.gain.value = 0;

            const b4000 = ctx.createBiquadFilter();
            b4000.type = "peaking";
            b4000.frequency.value = 4000;
            b4000.Q.value = 1;
            b4000.gain.value = 0;

            const b14000 = ctx.createBiquadFilter();
            b14000.type = "highshelf";
            b14000.frequency.value = 14000;
            b14000.gain.value = 0;

            const gain = ctx.createGain();

            source.connect(b60);
            b60.connect(b230);
            b230.connect(b910);
            b910.connect(b4000);
            b4000.connect(b14000);
            b14000.connect(gain);
            gain.connect(ctx.destination);

            audioCtxRef.current = ctx;
            sourceNodeRef.current = source;
            gainNodeRef.current = gain;
            eqBandsRef.current = { b60, b230, b910, b4000, b14000 };
            return true;
        } catch {
            // Web Audio unavailable or blocked — both features silently
            // have no effect, native playback is completely unaffected.
            return false;
        }
    }, [videoRef]);

    useEffect(() => {
        if (state.volumeBoost > 1) ensureAudioGraph();
    }, [state.volumeBoost, ensureAudioGraph]);

    useEffect(() => {
        if (!gainNodeRef.current) return;
        // Native <video>.volume already covers the 0-1 range (synced
        // elsewhere) — the GainNode only needs to apply the EXTRA
        // multiplier above 1.0. At volumeBoost=1 this is a no-op gain of 1.
        gainNodeRef.current.gain.value = state.volumeBoost;
    }, [state.volumeBoost]);

    // ── 5-Band EQ ──────────────────────────────────────────────────────────────
    // state.eqBands = { b60, b230, b910, b4000, b14000 }, each in dB, range
    // roughly -12..+12 (matches UsePlayerState.jsx's EQ_PRESETS). Connects
    // the shared audio graph on first non-zero use, same lazy pattern as
    // volume boost.
    useEffect(() => {
        const { b60, b230, b910, b4000, b14000 } = state.eqBands || {};
        if (state.eqEnabled && (b60 || b230 || b910 || b4000 || b14000)) ensureAudioGraph();
    }, [state.eqBands, state.eqEnabled, ensureAudioGraph]);

    useEffect(() => {
        const bands = eqBandsRef.current;
        if (!bands.b60) return;
        const { b60 = 0, b230 = 0, b910 = 0, b4000 = 0, b14000 = 0 } = state.eqEnabled ? state.eqBands || {} : {};
        bands.b60.gain.value = b60;
        bands.b230.gain.value = b230;
        bands.b910.gain.value = b910;
        bands.b4000.gain.value = b4000;
        bands.b14000.gain.value = b14000;
    }, [state.eqBands, state.eqEnabled]);

    // ── Sync playback speed ───────────────────────────────────────────────────
    useEffect(() => {
        if (videoRef.current) {
            videoRef.current.playbackRate = state.playbackSpeed;
        }
    }, [state.playbackSpeed]);

    // ── Sync play/pause ───────────────────────────────────────────────────────
    useEffect(() => {
        const video = videoRef.current;
        if (!video) return;
        if (state.playing) {
            video.play().catch(() => {});
        } else {
            video.pause();
        }
    }, [state.playing]);

    // ── Sync volume / mute ────────────────────────────────────────────────────
    useEffect(() => {
        if (videoRef.current) {
            videoRef.current.volume = state.volume;
            videoRef.current.muted = state.muted;
        }
    }, [state.volume, state.muted]);

    // ── Native video event handlers ───────────────────────────────────────────

    const handleTimeUpdate = () => {
        const v = videoRef.current;
        if (!v) return;
        actions.setCurrentTime(v.currentTime);
        actions.setBuffered(v.buffered);
    };

    const handleDurationChange = () => {
        const dur = videoRef.current?.duration;
        if (dur && isFinite(dur) && dur > 0) actions.setDuration(dur);
    };

    const handlePlay = () => {
        actions.setError(null);
        actions.setPlaying(true);
    };
    const handlePause = () => actions.setPlaying(false);

    const handleWaiting = () => {
        actions.setBuffering(true);
        actions.incrementStall();
    };

    const handleCanPlay = () => {
        actions.setBuffering(false);
        actions.setReady(true);
        actions.setError(null);
    };

    const handleProgress = () => {
        if (videoRef.current) actions.setBuffered(videoRef.current.buffered);
    };

    const handleEnded = () => {
        actions.setPlaying(false);
        if (state.loop === "one" && videoRef.current) {
            videoRef.current.currentTime = 0;
            videoRef.current.play().catch(() => {});
        }
    };

    const handleError = () => {
        const video = videoRef.current;
        if (!video?.error) return;

        // FIX (Report-06): When HLS.js is active, the <video> element's native
        // onerror fires because Chrome's demuxer rejects the malformed segment
        // (e.g. h264 without Annex B). The HLS.js ERROR event handler on the hls
        // instance is the correct place to handle this — it will call
        // hls.recoverMediaError() which swaps the SourceBuffer cleanly.
        //
        // Doing video.src = "" here destroys the MediaSource blob URL that HLS.js
        // created, breaking HLS.js irrecoverably. So when HLS is active: bail out
        // completely and let HLS.js's own ERROR handler deal with it.
        if (hlsRef.current) return;

        // Direct-play only below
        if (video.error?.code === MediaError.MEDIA_ERR_ABORTED) return;

        if (retryCount.current < 2) {
            retryCount.current++;
            const src = video.src;
            video.src = "";
            video.load();
            setTimeout(() => {
                if (videoRef.current) {
                    videoRef.current.src = src;
                    videoRef.current.load();
                    videoRef.current.play().catch(() => {});
                }
            }, 500);
        } else {
            actions.setError("Video playback error. Check the stream.");
        }
    };

    const handleVolumeChange = () => {
        if (videoRef.current) {
            actions.setVolume(videoRef.current.volume);
            actions.setMuted(videoRef.current.muted);
        }
    };

    // For "auto" (default) mode: compute exact letterbox pixel box from real
    // intrinsic dims + real container dims — no object-fit ambiguity, no
    // top-anchoring on ultra-wide/cinematic content. 16:9/4:3 get the same
    // pixel-exact treatment (computeFixedRatioBox) so they can't leave an
    // uneven gap either. fill/stretch/1:1 are left on CSS object-fit since
    // they intentionally ignore native ratio / are symmetric by construction.
    // Brightness gesture range is clamped to [0.3, 2.0] in PlayerGestures
    // (1.0 = neutral/native). A scrim can only ever subtract light — it has
    // no way to push past whatever the screen's actual current backlight is
    // — so values above 1.0 are full-clear (0 scrim, same as 1.0) and values
    // below 1.0 ramp the scrim up toward the spec's 0.85 max-dim ceiling.
    const userBrightnessPct = Math.min(1, state.brightness); // 0.3-1.0 → 0.3-1.0, anything above 1.0 clamps to 1.0 (no scrim)
    const brightnessScrimOpacity = Math.max(0, Math.min(0.85, 1 - userBrightnessPct));

    const isAutoMode = state.aspectRatio === "auto" || !state.aspectRatio;
    const isFixedRatioMode = state.aspectRatio === "16:9" || state.aspectRatio === "4:3";
    const computedBox = isAutoMode ? computeLetterboxBox(containerDims.w, containerDims.h, videoDims.w, videoDims.h) : null;
    const fixedRatioBox = isFixedRatioMode ? computeFixedRatioBox(containerDims.w, containerDims.h, state.aspectRatio === "16:9" ? 16 : 4, state.aspectRatio === "16:9" ? 9 : 3) : null;

    const hasIntrinsicDims = videoDims.w > 0 && videoDims.h > 0 && containerDims.w > 0 && containerDims.h > 0;
    const hasContainerDims = containerDims.w > 0 && containerDims.h > 0;

    const videoStyle = isAutoMode
        ? hasIntrinsicDims
            ? {
                  width: computedBox.width,
                  height: computedBox.height,
                  objectFit: "fill", // box is already exact letterbox size — no further fit needed
              }
            : {
                  // Pre-metadata fallback: contain avoids a stretch flash before
                  // real dims are known. Box is briefly ambiguous but corrects
                  // itself the instant loadedmetadata fires (no visible jump
                  // since both produce a centered, non-stretched result).
                  width: "100%",
                  height: "100%",
                  objectFit: "contain",
              }
        : isFixedRatioMode
          ? hasContainerDims
              ? {
                    width: fixedRatioBox.width,
                    height: fixedRatioBox.height,
                    objectFit: "fill", // box is already exact target-ratio size
                    transition: "width 0.2s ease-out, height 0.2s ease-out", // smooth resize when cycling modes
                }
              : { width: "100%", height: "100%", objectFit: "contain" } // pre-layout fallback before container is measured
          : getAspectStyle(state.aspectRatio);

    return (
        // FIX: outer wrapper is flex-centered absolute inset-0 so the video box
        // stays centered inside whatever box the parent (fixed/fullscreen)
        // container resolves to — no fixed vh units here that could mismatch
        // native Fullscreen API sizing on Android Chrome.
        <div
            ref={wrapperRef}
            style={{
                position: "absolute",
                inset: 0,
                width: "100%",
                height: "100%",
                display: "grid",
                placeItems: "center",
                overflow: "hidden",
            }}>
            <video
                ref={videoRef}
                style={{
                    ...videoStyle,
                    background: "#000",
                    display: "block",
                    margin: "auto",
                    justifySelf: "center",
                    alignSelf: "center",
                    // Real pinch-zoom: scale + pan via transform, anchored center.
                    // Pan only meaningful once zoomScale > 1 (enforced by caller).
                    transform: `translate3d(${panX}px, ${panY}px, 0) scale(${zoomScale})`,
                    transformOrigin: "center center",
                    // FIX: "contents" is not a valid will-change pairing here
                    // and some Android WebView/Chrome builds have a known bug
                    // where a GPU compositing layer created at a larger
                    // transform:scale() doesn't properly repaint smaller on
                    // shrink — it can visually stick at the bigger size even
                    // though the transform value did update. willChange:
                    // "transform" alone (not "contents") avoids creating an
                    // ambiguous layer hint and lets the browser correctly
                    // re-rasterize on both grow and shrink.
                    willChange: "transform",
                }}
                playsInline
                preload="auto"
                crossOrigin="anonymous"
                onClick={onVideoClick}
                onTimeUpdate={handleTimeUpdate}
                onDurationChange={handleDurationChange}
                onPlay={handlePlay}
                onPause={handlePause}
                onWaiting={handleWaiting}
                onCanPlay={handleCanPlay}
                onEnded={handleEnded}
                onError={handleError}
                onVolumeChange={handleVolumeChange}
                onProgress={handleProgress}
                onStalled={() => {
                    actions.setBuffering(true);
                    actions.incrementStall();
                }}
                onSeeking={() => actions.setBuffering(true)}
                onSeeked={() => actions.setBuffering(false)}
            />
            {/* ── Brightness scrim ─────────────────────────────────────────────
                Pure black layer, NOT a CSS filter on the video — a filter
                mutates the actual pixel data (burns whites, flattens blacks,
                reads as "contrast" instead of "brightness"). This sits on
                top of the video and underneath the gesture/HUD layer instead,
                so dimming is achieved by occlusion, not texture manipulation.
                The video's own color space, saturation, and contrast are
                completely untouched regardless of state.brightness. */}
            <div
                style={{
                    position: "absolute",
                    inset: 0,
                    background: "#000",
                    opacity: brightnessScrimOpacity,
                    pointerEvents: "none",
                    transition: "opacity 80ms linear",
                }}
            />
        </div>
    );
});

export default VideoCore;
